export type ModelKey = 'kepler' | 'k2' | 'tess';
type ColInfo = { description: string; type: 'float' | 'int' | 'string' };

export const FEATURE_MAP: Record<ModelKey, Record<string, ColInfo>> = {
  kepler: {
    koi_period: { description: 'Orbital period (days)', type: 'float' },
    koi_eccen: { description: 'Orbital eccentricity', type: 'float' },
    koi_longp: { description: 'Longitude of periastron (degrees)', type: 'float' },
    koi_impact: { description: 'Transit impact parameter', type: 'float' },
    koi_duration: { description: 'Transit duration (hours)', type: 'float' },
    koi_ingress: { description: 'Transit ingress duration (hours)', type: 'float' },
    koi_depth: { description: 'Transit depth (ppm)', type: 'float' },
    koi_ror: { description: 'Planet-to-star radius ratio (Rp/Rs)', type: 'float' },
    koi_srho: { description: 'Stellar density (g/cm³)', type: 'float' },
    koi_prad: { description: 'Planet radius (Earth radii)', type: 'float' },
    koi_sma: { description: 'Semi-major axis (AU)', type: 'float' },
    koi_incl: { description: 'Orbital inclination (degrees)', type: 'float' },
    koi_teq: { description: 'Equilibrium temperature (K)', type: 'float' },
    koi_insol: { description: 'Incident flux (⊕)', type: 'float' },
    koi_dor: { description: 'Distance between star and planet centers (stellar radii)', type: 'float' },
    koi_ldm_coeff4: { description: 'Limb darkening coefficient 4', type: 'float' },
    koi_ldm_coeff3: { description: 'Limb darkening coefficient 3', type: 'float' },
    koi_ldm_coeff2: { description: 'Limb darkening coefficient 2', type: 'float' },
    koi_ldm_coeff1: { description: 'Limb darkening coefficient 1', type: 'float' },
    koi_max_sngle_ev: { description: 'Max single event statistic', type: 'float' },
    koi_max_mult_ev: { description: 'Max multiple event statistic', type: 'float' },
    koi_model_snr: { description: 'Transit model signal-to-noise ratio', type: 'float' },
    koi_count: { description: 'Number of transits observed', type: 'int' },
    koi_num_transits: { description: 'Number of detected transits', type: 'int' },
    koi_tce_plnt_num: { description: 'TCE planet number', type: 'int' },
    koi_bin_oedp_sig: { description: 'Odd-even depth difference significance', type: 'float' },
    koi_model_dof: { description: 'Degrees of freedom in transit model', type: 'int' },
    koi_model_chisq: { description: 'Chi-squared of transit model', type: 'float' },
    koi_steff: { description: 'Stellar effective temperature (K)', type: 'float' },
    koi_slogg: { description: 'Surface gravity (log g)', type: 'float' },
    koi_smet: { description: 'Stellar metallicity ([Fe/H])', type: 'float' },
    koi_srad: { description: 'Stellar radius (R☉)', type: 'float' },
    koi_smass: { description: 'Stellar mass (M☉)', type: 'float' },
    koi_sage: { description: 'Stellar age (Gyr)', type: 'float' },
    ra: { description: 'Right ascension (deg)', type: 'float' },
    dec: { description: 'Declination (deg)', type: 'float' },
    koi_kepmag: { description: 'Kepler magnitude', type: 'float' },
    koi_gmag: { description: 'Gaia G magnitude', type: 'float' },
    koi_rmag: { description: 'r-band magnitude', type: 'float' },
    koi_imag: { description: 'i-band magnitude', type: 'float' },
    koi_zmag: { description: 'z-band magnitude', type: 'float' },
    koi_jmag: { description: 'J-band magnitude', type: 'float' },
    koi_hmag: { description: 'H-band magnitude', type: 'float' },
    koi_kmag: { description: 'K-band magnitude', type: 'float' },
    koi_fwm_stat_sig: { description: 'Centroid offset significance', type: 'float' },
    koi_fwm_sra: { description: 'Source RA offset (arcsec)', type: 'float' },
    koi_fwm_sdec: { description: 'Source Dec offset (arcsec)', type: 'float' },
    koi_fwm_srao: { description: 'Out-of-transit RA offset (arcsec)', type: 'float' },
    koi_fwm_sdeco: { description: 'Out-of-transit Dec offset (arcsec)', type: 'float' },
    koi_fwm_prao: { description: 'Photocenter RA offset (arcsec)', type: 'float' },
    koi_fwm_pdeco: { description: 'Photocenter Dec offset (arcsec)', type: 'float' },
    koi_dicco_mra: { description: 'Difference image centroid RA (arcsec)', type: 'float' },
    koi_dicco_mdec: { description: 'Difference image centroid Dec (arcsec)', type: 'float' },
    koi_dicco_msky: { description: 'Difference image centroid offset (arcsec)', type: 'float' },
    koi_dikco_mra: { description: 'Difference image kernel RA (arcsec)', type: 'float' },
    koi_dikco_mdec: { description: 'Difference image kernel Dec (arcsec)', type: 'float' },
    koi_dikco_msky: { description: 'Difference image kernel offset (arcsec)', type: 'float' },
    koi_fittype: { description: 'Transit model fitting type', type: 'string' },
    koi_parm_prov: { description: 'Parameter provenance', type: 'string' },
    koi_tce_delivname: { description: 'TCE delivery name', type: 'string' },
    koi_sparprov: { description: 'Stellar parameter provenance', type: 'string' },
  },

  k2: {
    st_dens: { description: 'Stellar density (g/cm³)', type: 'float' },
    pl_cmasse: { description: 'Calculated planet mass (Earth masses)', type: 'float' },
    sy_kepmag: { description: 'Kepler magnitude', type: 'float' },
    st_radv: { description: 'Stellar radial velocity (km/s)', type: 'float' },
    pl_orbsmax: { description: 'Semi-major axis (AU)', type: 'float' },
    pl_dens: { description: 'Planet density (g/cm³)', type: 'float' },
    pl_massj: { description: 'Planet mass (Jupiter masses)', type: 'float' },
    pl_insol: { description: 'Incident flux (⊕)', type: 'float' },
    pl_bmasse: { description: 'Best-fit planet mass (Earth masses)', type: 'float' },
    ra: { description: 'Right ascension (deg)', type: 'float' },
    pl_trandep: { description: 'Transit depth (ppm)', type: 'float' },
    st_logg: { description: 'Surface gravity (log g)', type: 'float' },
    sy_bmag: { description: 'B-band magnitude', type: 'float' },
    st_age: { description: 'Stellar age (Gyr)', type: 'float' },
    pl_occdep: { description: 'Occultation depth (ppm)', type: 'float' },
    pl_orbeccen: { description: 'Orbital eccentricity', type: 'float' },
    sy_jmag: { description: 'J-band magnitude', type: 'float' },
    sy_kmag: { description: 'K-band magnitude', type: 'float' },
    elat: { description: 'Ecliptic latitude (deg)', type: 'float' },
    dec: { description: 'Declination (deg)', type: 'float' },
    sy_w1mag: { description: 'WISE W1 magnitude', type: 'float' },
    st_rad: { description: 'Stellar radius (R☉)', type: 'float' },
    pl_rvamp: { description: 'Radial velocity semi-amplitude (m/s)', type: 'float' },
    pl_bmassj: { description: 'Best-fit planet mass (Jupiter masses)', type: 'float' },
    pl_orblper: { description: 'Argument of periastron (deg)', type: 'float' },
    pl_tranmid: { description: 'Mid-transit time (BJD)', type: 'float' },
    sy_gmag: { description: 'Gaia G magnitude', type: 'float' },
    elon: { description: 'Ecliptic longitude (deg)', type: 'float' },
    sy_imag: { description: 'i-band magnitude', type: 'float' },
    st_rotp: { description: 'Stellar rotation period (days)', type: 'float' },
    pl_msinij: { description: 'Planet mass × sin(i) (Jupiter masses)', type: 'float' },
    pl_orbtper: { description: 'Time of periastron passage (BJD)', type: 'float' },
    sy_pm: { description: 'Proper motion (mas/yr)', type: 'float' },
    st_teff: { description: 'Stellar effective temperature (K)', type: 'float' },
    pl_orbper: { description: 'Orbital period (days)', type: 'float' },
    sy_plx: { description: 'Parallax (mas)', type: 'float' },
    sy_umag: { description: 'u-band magnitude', type: 'float' },
    pl_cmassj: { description: 'Calculated planet mass (Jupiter masses)', type: 'float' },
    pl_eqt: { description: 'Equilibrium temperature (K)', type: 'float' },
    sy_gaiamag: { description: 'Gaia absolute magnitude', type: 'float' },
    st_mass: { description: 'Stellar mass (M☉)', type: 'float' },
    pl_masse: { description: 'Planet mass (Earth masses)', type: 'float' },
    sy_rmag: { description: 'r-band magnitude', type: 'float' },
    sy_dist: { description: 'System distance (pc)', type: 'float' },
    sy_zmag: { description: 'z-band magnitude', type: 'float' },
    pl_orbincl: { description: 'Orbital inclination (deg)', type: 'float' },
    sy_pmdec: { description: 'Proper motion in declination (mas/yr)', type: 'float' },
    st_met: { description: 'Stellar metallicity ([Fe/H])', type: 'float' },
    glat: { description: 'Galactic latitude (deg)', type: 'float' },
    sy_w4mag: { description: 'WISE W4 magnitude', type: 'float' },
    pl_imppar: { description: 'Impact parameter', type: 'float' },
    ttv_flag: { description: 'Transit timing variations flag', type: 'int' },
    pl_projobliq: { description: 'Projected obliquity (deg)', type: 'float' },
    st_lum: { description: 'Stellar luminosity (L☉)', type: 'float' },
    sy_pmra: { description: 'Proper motion in RA (mas/yr)', type: 'float' },
    pl_trueobliq: { description: 'True obliquity (deg)', type: 'float' },
    pl_ratror: { description: 'Planet-to-star radius ratio', type: 'float' },
    sy_icmag: { description: 'Ic-band magnitude', type: 'float' },
    pl_rade: { description: 'Planet radius (Earth radii)', type: 'float' },
    pl_trandur: { description: 'Transit duration (hours)', type: 'float' },
    sy_hmag: { description: 'H-band magnitude', type: 'float' },
    glon: { description: 'Galactic longitude (deg)', type: 'float' },
    pl_radj: { description: 'Planet radius (Jupiter radii)', type: 'float' },
    st_vsin: { description: 'Projected rotational velocity (km/s)', type: 'float' },
    sy_w2mag: { description: 'WISE W2 magnitude', type: 'float' },
    sy_vmag: { description: 'V-band magnitude', type: 'float' },
    pl_msinie: { description: 'Planet mass × sin(i) (Earth masses)', type: 'float' },
    sy_tmag: { description: 'TESS magnitude', type: 'float' },
    pl_ratdor: { description: 'Planet-star distance ratio (a/Rs)', type: 'float' },
    sy_w3mag: { description: 'WISE W3 magnitude', type: 'float' },
},

  tess: {
    st_pmra: { description: 'Star motion east–west', type: 'float' },
    st_pmdec:{ description: 'Star motion north–south', type: 'float' },
    pl_orbper:{ description: 'Planet orbital period (days)', type: 'float' },
    pl_trandurh:{ description: 'Transit duration (hours)', type: 'float' },
    pl_trandep:{ description: 'Transit depth (ppm)', type: 'float' },
    pl_rade:{ description: 'Planet radius (R⊕)', type: 'float' },
    pl_insol:{ description: 'Starlight received (⊕)', type: 'float' },
    pl_eqt:{ description: 'Equilibrium temperature (K)', type: 'float' },
    st_tmag:{ description: 'TESS magnitude', type: 'float' },
    st_dist:{ description: 'Distance (pc)', type: 'float' },
    st_teff:{ description: 'Star effective temperature (K)', type: 'float' },
    st_logg:{ description: 'Surface gravity (log g)', type: 'float' },
    st_rad:{ description: 'Star radius (R☉)', type: 'float' },
    pl_pnum:{ description: 'Number of planet candidates', type: 'int' },
  },
};

export const FEATURE_ORDER: Record<ModelKey, string[]> = {
  kepler: ['koi_period','koi_duration','koi_depth','koi_prad','koi_teq','koi_insol'],
  k2:     [],
  tess:   ['st_pmra','st_pmdec','pl_orbper','pl_trandurh','pl_trandep','pl_rade','pl_insol','pl_eqt','st_tmag','st_dist','st_teff','st_logg','st_rad','pl_pnum'],
};
